/**
 * UDAF Grouping — /api/tenants/udafs with grouping.enable=true
 *
 * KEY DISCOVERIES:
 * - `grouping` must be an object, never a boolean
 * - `take` must be "FIRST" or "LAST" when enable=true
 * - Missing `take` when enable=true crashes server with 500 (BUG-075)
 * - `mfieldId` in grouping.field is auto-generated by server (returned != input)
 * - Response `params` drops displayName and mfieldId — only fieldName survives roundtrip
 * - `timeWindow` is stored as {} regardless of input (BUG-046)
 * - UDAF calculate is universally broken for ALL UDAFs (BUG-049) — skipped here
 *
 * Tests:
 * 1. CREATE — all aggTypes with grouping enabled
 * 2. GET — verify grouping fields persist correctly
 * 3. Grouping validation — missing/invalid fields
 * 4. Grouping + params interaction
 * 5. Grouping edge cases
 * 6. Calculate with grouped UDAF (BUG-049 documented)
 * 7. Cleanup
 */
import { describe, it, expect } from "vitest";
import { get, post } from "./client";

const TS = Date.now();
const PURCHASE_EVENT = { id: 100 };

// Known varchar field on purchase event (used for grouping field)
const GROUP_FIELD = {
  fieldName: "col__varchar_s50000__0",
  displayName: "First Name",
  mfieldId: "00000000-0000-0000-0000-000000000002",
};

// Known bigint field on purchase event (used as params for non-COUNT UDAFs)
const PARAM_FIELD = {
  fieldName: "col__bigint__1",
  displayName: "Phone",
  mfieldId: "00000000-0000-0000-0000-000000000001",
};

// Known double field on purchase event (used as params for SUM/AVG/MIN/MAX)
const DOUBLE_FIELD = {
  fieldName: "col__double__0",
  displayName: "Total Price",
  mfieldId: "c9fc80bc-dad2-49bb-a158-9009a2c27b9d",
};

// Track created UDAFs for cleanup
const createdIds: string[] = [];

// ─── Helpers ────────────────────────────────────────────────────────────────

function makeGroupedUdaf(
  name: string,
  aggType: string,
  take: "FIRST" | "LAST",
  params: { fieldName: string; displayName: string; mfieldId: string }[] = [],
) {
  return {
    name,
    aggType,
    filter: {
      eventType: PURCHASE_EVENT,
      predicate: {
        type: "group",
        group: { logicalOp: "AND", negate: false, predicates: [] },
      },
      timeWindow: { type: "ABSOLUTE", absoluteTime: "2025-01-01T00:00:00Z" },
    },
    grouping: {
      enable: true,
      field: GROUP_FIELD,
      take,
    },
    params,
  };
}

function makeUngroupedUdaf(name: string, aggType: string) {
  return {
    name,
    aggType,
    filter: {
      eventType: PURCHASE_EVENT,
      predicate: {
        type: "group",
        group: { logicalOp: "AND", negate: false, predicates: [] },
      },
      timeWindow: { type: "ABSOLUTE", absoluteTime: "2025-01-01T00:00:00Z" },
    },
    grouping: { enable: false },
    params: [],
  };
}

// ─── Test Suite ─────────────────────────────────────────────────────────────

describe("UDAF Grouping — /api/tenants/udafs", () => {

  // ── 1. CREATE — all aggTypes with grouping enabled ────────────────────────

  describe("1. CREATE with grouping enabled", () => {

    it("should create SUM UDAF with grouping take=LAST", async () => {
      const name = `s23_group_${TS}_sum_last`;
      const payload = makeGroupedUdaf(name, "SUM", "LAST", [
        { fieldName: DOUBLE_FIELD.fieldName, displayName: DOUBLE_FIELD.displayName, mfieldId: DOUBLE_FIELD.mfieldId },
      ]);

      const { status, data } = await post("/api/tenants/udafs", payload);

      expect([200, 201]).toContain(status);
      expect(data).toBeDefined();
      expect(data.aggType).toBe("SUM");
      if (data?.id) createdIds.push(data.id);
    });

    it("should create COUNT UDAF with grouping take=FIRST", async () => {
      const name = `s23_group_${TS}_count_first`;
      const payload = makeGroupedUdaf(name, "COUNT", "FIRST");

      const { status, data } = await post("/api/tenants/udafs", payload);

      expect([200, 201]).toContain(status);
      expect(data).toBeDefined();
      expect(data.aggType).toBe("COUNT");
      if (data?.id) createdIds.push(data.id);
    });

    it("should create AVG UDAF with grouping", async () => {
      const name = `s23_group_${TS}_avg`;
      const payload = makeGroupedUdaf(name, "AVG", "LAST", [
        { fieldName: DOUBLE_FIELD.fieldName, displayName: DOUBLE_FIELD.displayName, mfieldId: DOUBLE_FIELD.mfieldId },
      ]);

      const { status, data } = await post("/api/tenants/udafs", payload);

      expect([200, 201]).toContain(status);
      if (data?.id) createdIds.push(data.id);
    });

    it("should create MIN UDAF with grouping", async () => {
      const name = `s23_group_${TS}_min`;
      const payload = makeGroupedUdaf(name, "MIN", "LAST", [
        { fieldName: DOUBLE_FIELD.fieldName, displayName: DOUBLE_FIELD.displayName, mfieldId: DOUBLE_FIELD.mfieldId },
      ]);

      const { status, data } = await post("/api/tenants/udafs", payload);

      expect([200, 201]).toContain(status);
      if (data?.id) createdIds.push(data.id);
    });

    it("should create MAX UDAF with grouping", async () => {
      const name = `s23_group_${TS}_max`;
      const payload = makeGroupedUdaf(name, "MAX", "FIRST", [
        { fieldName: DOUBLE_FIELD.fieldName, displayName: DOUBLE_FIELD.displayName, mfieldId: DOUBLE_FIELD.mfieldId },
      ]);

      const { status, data } = await post("/api/tenants/udafs", payload);

      expect([200, 201]).toContain(status);
      if (data?.id) createdIds.push(data.id);
    });

  });

  // ── 2. GET — verify grouping fields persist correctly ────────────────────

  describe("2. GET — grouping fields persist in stored definition", () => {

    it("should persist grouping.enable, field.fieldName, and take in GET response", async () => {
      // Use the SUM UDAF created in section 1 (first entry)
      const udafId = createdIds[0];
      if (!udafId) {
        console.log("SKIP: SUM grouped UDAF was not created");
        return;
      }

      const { status, data } = await get(`/api/tenants/udafs/${udafId}`);

      expect(status).toBe(200);
      expect(data.grouping).toBeDefined();
      expect(data.grouping.enable).toBe(true);
      expect(data.grouping.field?.fieldName).toBe(GROUP_FIELD.fieldName);
      expect(data.grouping.take).toBe("LAST");
    });

    it("should auto-generate mfieldId — returned value differs from input", async () => {
      const udafId = createdIds[0];
      if (!udafId) {
        console.log("SKIP: SUM grouped UDAF was not created");
        return;
      }

      const { status, data } = await get(`/api/tenants/udafs/${udafId}`);

      expect(status).toBe(200);
      // Server auto-generates the mfieldId for the grouping field
      const returnedMfieldId = data.grouping?.field?.mfieldId;
      if (returnedMfieldId !== undefined) {
        // If server returns it, it should be a valid UUID but not the one we sent
        const isUuidFormat = /^[0-9a-f-]{36}$/i.test(returnedMfieldId);
        if (isUuidFormat) {
          expect(returnedMfieldId).not.toBe(GROUP_FIELD.mfieldId);
          console.log(`mfieldId auto-generated: input=${GROUP_FIELD.mfieldId}, returned=${returnedMfieldId}`);
        } else {
          console.log(`FINDING: returned mfieldId is not UUID format: ${returnedMfieldId}`);
        }
      } else {
        console.log("FINDING: grouping.field.mfieldId not returned in GET response");
      }
    });

    it("should verify params roundtrip — only fieldName survives (displayName/mfieldId dropped)", async () => {
      const udafId = createdIds[0];
      if (!udafId) {
        console.log("SKIP: SUM grouped UDAF was not created");
        return;
      }

      const { status, data } = await get(`/api/tenants/udafs/${udafId}`);

      expect(status).toBe(200);
      expect(Array.isArray(data.params)).toBe(true);
      if (data.params.length > 0) {
        const param = data.params[0];
        expect(param.fieldName).toBe(DOUBLE_FIELD.fieldName);
        // displayName and mfieldId are dropped by server
        if (param.displayName === undefined && param.mfieldId === undefined) {
          console.log("CONFIRMED: params response drops displayName and mfieldId — only fieldName returned");
        } else {
          console.log(`FINDING: params returned with extra fields: ${JSON.stringify(param)}`);
        }
      }
    });

    it("should verify timeWindow is stored as {} (BUG-046)", async () => {
      const udafId = createdIds[0];
      if (!udafId) {
        console.log("SKIP: SUM grouped UDAF was not created");
        return;
      }

      const { status, data } = await get(`/api/tenants/udafs/${udafId}`);

      expect(status).toBe(200);
      const tw = data.filter?.timeWindow;
      if (tw && Object.keys(tw).length === 0) {
        console.log("CONFIRMED: BUG-046 — timeWindow stored as {} regardless of ABSOLUTE input");
      } else {
        console.log(`timeWindow stored as: ${JSON.stringify(tw)}`);
      }
    });

  });

  // ── 3. Grouping validation ────────────────────────────────────────────────

  describe("3. Grouping validation", () => {

    it("should reject grouping as boolean true (400 — must be object)", async () => {
      const name = `s23_group_${TS}_bool_true`;
      const payload = {
        name,
        aggType: "COUNT",
        filter: {
          eventType: PURCHASE_EVENT,
          predicate: { type: "group", group: { logicalOp: "AND", negate: false, predicates: [] } },
          timeWindow: {},
        },
        grouping: true, // invalid — must be object
        params: [],
      };

      const { status } = await post("/api/tenants/udafs", payload);
      expect([400, 422]).toContain(status);
    });

    it("should reject grouping as boolean false (400 — must be object)", async () => {
      const name = `s23_group_${TS}_bool_false`;
      const payload = {
        name,
        aggType: "COUNT",
        filter: {
          eventType: PURCHASE_EVENT,
          predicate: { type: "group", group: { logicalOp: "AND", negate: false, predicates: [] } },
          timeWindow: {},
        },
        grouping: false, // invalid — must be object
        params: [],
      };

      const { status } = await post("/api/tenants/udafs", payload);
      expect([400, 422]).toContain(status);
    });

    it("should reject missing take when enable=true (BUG-075: expect 400, actual 500)", async () => {
      const name = `s23_group_${TS}_no_take`;
      const payload = {
        name,
        aggType: "COUNT",
        filter: {
          eventType: PURCHASE_EVENT,
          predicate: { type: "group", group: { logicalOp: "AND", negate: false, predicates: [] } },
          timeWindow: {},
        },
        grouping: {
          enable: true,
          field: GROUP_FIELD,
          // take intentionally omitted
        },
        params: [],
      };

      // BUG-075: Missing take when grouping enabled crashes server (should be 400)
      const { status } = await post("/api/tenants/udafs", payload);
      expect([400, 500]).toContain(status); // 500 = BUG-075
      if (status === 500) {
        console.warn("BUG-075: Missing take crashes server instead of returning 400");
      }
    });

    it("should reject invalid take value 'MIDDLE' (400 from OpenAPI validation)", async () => {
      const name = `s23_group_${TS}_bad_take`;
      const payload = {
        name,
        aggType: "COUNT",
        filter: {
          eventType: PURCHASE_EVENT,
          predicate: { type: "group", group: { logicalOp: "AND", negate: false, predicates: [] } },
          timeWindow: {},
        },
        grouping: {
          enable: true,
          field: GROUP_FIELD,
          take: "MIDDLE", // invalid
        },
        params: [],
      };

      const { status } = await post("/api/tenants/udafs", payload);
      expect([400, 422]).toContain(status);
    });

    it("should reject invalid take value 'RANDOM' (400 from OpenAPI validation)", async () => {
      const name = `s23_group_${TS}_bad_take2`;
      const payload = {
        name,
        aggType: "COUNT",
        filter: {
          eventType: PURCHASE_EVENT,
          predicate: { type: "group", group: { logicalOp: "AND", negate: false, predicates: [] } },
          timeWindow: {},
        },
        grouping: {
          enable: true,
          field: GROUP_FIELD,
          take: "RANDOM", // invalid
        },
        params: [],
      };

      const { status } = await post("/api/tenants/udafs", payload);
      expect([400, 422]).toContain(status);
    });

    it("should accept enable=false without field or take", async () => {
      const name = `s23_group_${TS}_disabled`;
      const payload = makeUngroupedUdaf(name, "COUNT");

      const { status, data } = await post("/api/tenants/udafs", payload);

      expect([200, 201]).toContain(status);
      if (data?.id) createdIds.push(data.id);
    });

    it("should reject missing field when enable=true (expect 400 or 500)", async () => {
      const name = `s23_group_${TS}_no_field`;
      const payload = {
        name,
        aggType: "COUNT",
        filter: {
          eventType: PURCHASE_EVENT,
          predicate: { type: "group", group: { logicalOp: "AND", negate: false, predicates: [] } },
          timeWindow: {},
        },
        grouping: {
          enable: true,
          // field intentionally omitted
          take: "LAST",
        },
        params: [],
      };

      const { status } = await post("/api/tenants/udafs", payload);
      // Missing required field when enabled — should be 400, may be 500
      expect([400, 500]).toContain(status);
      if (status === 500) {
        console.warn("FINDING: Missing grouping.field when enable=true crashes server (500)");
      }
    });

  });

  // ── 4. Grouping + params interaction ─────────────────────────────────────

  describe("4. Grouping + params interaction", () => {

    it("SUM with grouping should require params (fieldName)", async () => {
      const name = `s23_group_${TS}_sum_no_params`;
      const payload = makeGroupedUdaf(name, "SUM", "LAST"); // No params

      const { status, data } = await post("/api/tenants/udafs", payload);

      if (status === 409) {
        console.log("Correctly rejected SUM with grouping but no params: 409");
      } else if (status === 200 || status === 201) {
        console.log("FINDING: SUM with grouping accepted without params — unexpected");
        if (data?.id) createdIds.push(data.id);
      } else {
        console.log(`SUM grouping no-params response: HTTP ${status}`);
      }
      // Accept any response — we're documenting behavior
      expect([200, 201, 400, 409]).toContain(status);
    });

    it("COUNT with grouping should work with empty params", async () => {
      const name = `s23_group_${TS}_count_no_params`;
      const payload = makeGroupedUdaf(name, "COUNT", "FIRST"); // No params needed for COUNT

      const { status, data } = await post("/api/tenants/udafs", payload);

      expect([200, 201]).toContain(status);
      if (data?.id) createdIds.push(data.id);
    });

    it("should preserve params fieldName in roundtrip (GET after CREATE)", async () => {
      const name = `s23_group_${TS}_params_roundtrip`;
      const payload = makeGroupedUdaf(name, "SUM", "LAST", [
        { fieldName: PARAM_FIELD.fieldName, displayName: PARAM_FIELD.displayName, mfieldId: PARAM_FIELD.mfieldId },
      ]);

      const { status: createStatus, data: created } = await post("/api/tenants/udafs", payload);

      if (createStatus !== 200 && createStatus !== 201) {
        console.log(`SKIP: roundtrip CREATE failed HTTP ${createStatus}`);
        return;
      }
      const udafId = created?.id;
      if (!udafId) return;
      createdIds.push(udafId);

      const { status: getStatus, data: fetched } = await get(`/api/tenants/udafs/${udafId}`);

      expect(getStatus).toBe(200);
      expect(Array.isArray(fetched.params)).toBe(true);
      expect(fetched.params.length).toBeGreaterThan(0);
      expect(fetched.params[0].fieldName).toBe(PARAM_FIELD.fieldName);
      console.log(`Params roundtrip: input fieldName=${PARAM_FIELD.fieldName}, returned=${fetched.params[0].fieldName}`);
    });

  });

  // ── 5. Grouping edge cases ────────────────────────────────────────────────

  describe("5. Grouping edge cases", () => {

    it("should reject or accept grouping field with non-existent fieldName (expect 200 — no validation)", async () => {
      const name = `s23_group_${TS}_bad_fieldname`;
      const payload = {
        name,
        aggType: "COUNT",
        filter: {
          eventType: PURCHASE_EVENT,
          predicate: { type: "group", group: { logicalOp: "AND", negate: false, predicates: [] } },
          timeWindow: {},
        },
        grouping: {
          enable: true,
          field: {
            fieldName: "col__nonexistent__99",
            displayName: "Does Not Exist",
            mfieldId: "00000000-0000-0000-0000-000000000099",
          },
          take: "LAST",
        },
        params: [],
      };

      const { status, data } = await post("/api/tenants/udafs", payload);

      if (status === 200 || status === 201) {
        console.log("FINDING: grouping field with non-existent fieldName accepted — no server-side validation");
        if (data?.id) createdIds.push(data.id);
      } else {
        console.log(`Non-existent grouping fieldName rejected: HTTP ${status}`);
      }
      // Accept any — documenting
      expect([200, 201, 400, 409]).toContain(status);
    });

    it("should handle empty string fieldName in grouping", async () => {
      const name = `s23_group_${TS}_empty_fieldname`;
      const payload = {
        name,
        aggType: "COUNT",
        filter: {
          eventType: PURCHASE_EVENT,
          predicate: { type: "group", group: { logicalOp: "AND", negate: false, predicates: [] } },
          timeWindow: {},
        },
        grouping: {
          enable: true,
          field: {
            fieldName: "",
            displayName: "",
            mfieldId: "00000000-0000-0000-0000-000000000000",
          },
          take: "LAST",
        },
        params: [],
      };

      const { status, data } = await post("/api/tenants/udafs", payload);

      if (status === 200 || status === 201) {
        console.log("FINDING: Empty string grouping fieldName accepted — no validation");
        if (data?.id) createdIds.push(data.id);
      } else {
        console.log(`Empty grouping fieldName rejected: HTTP ${status}: ${JSON.stringify(data).substring(0, 200)}`);
      }
      expect([200, 201, 400, 409, 422]).toContain(status);
    });

    it("should handle very long fieldName in grouping (255+ chars)", async () => {
      const name = `s23_group_${TS}_long_fieldname`;
      const longFieldName = "col__" + "a".repeat(300) + "__0";
      const payload = {
        name,
        aggType: "COUNT",
        filter: {
          eventType: PURCHASE_EVENT,
          predicate: { type: "group", group: { logicalOp: "AND", negate: false, predicates: [] } },
          timeWindow: {},
        },
        grouping: {
          enable: true,
          field: {
            fieldName: longFieldName,
            displayName: "Very Long Field",
            mfieldId: "00000000-0000-0000-0000-000000000000",
          },
          take: "FIRST",
        },
        params: [],
      };

      const { status, data } = await post("/api/tenants/udafs", payload);

      if (status === 200 || status === 201) {
        console.log(`FINDING: Long fieldName (${longFieldName.length} chars) accepted — no length validation`);
        if (data?.id) createdIds.push(data.id);
      } else {
        console.log(`Long fieldName rejected: HTTP ${status}`);
      }
      expect([200, 201, 400, 409, 413, 422]).toContain(status);
    });

    it("should accept both take=FIRST and take=LAST as valid values", async () => {
      for (const take of ["FIRST", "LAST"] as const) {
        const name = `s23_group_${TS}_take_${take.toLowerCase()}`;
        const payload = makeGroupedUdaf(name, "COUNT", take);

        const { status, data } = await post("/api/tenants/udafs", payload);

        expect([200, 201]).toContain(status);
        console.log(`take=${take}: HTTP ${status}`);
        if (data?.id) createdIds.push(data.id);
      }
    });

  });

  // ── 6. Calculate with grouped UDAF (BUG-049 — all broken) ────────────────

  describe("6. Calculate with grouped UDAF (BUG-049 — universally broken)", () => {

    it("should document that calculate returns 500 for grouped UDAFs (BUG-049)", async () => {
      // BUG-049: UDAF calculate endpoint is broken for ALL UDAFs, including grouped ones.
      // POST /api/tenants/udafs/{id}/calculate?primaryId=N always returns 500.
      // This test documents the behavior rather than asserting correctness.
      const udafId = createdIds[0]; // Use first grouped UDAF created
      if (!udafId) {
        console.log("SKIP: No grouped UDAF available to test calculate");
        return;
      }

      const { status, data } = await post(
        `/api/tenants/udafs/${udafId}/calculate`,
        undefined,
        { primaryId: 1 },
      );

      console.warn(
        `BUG-049: Calculate for grouped UDAF ${udafId} → HTTP ${status}. ` +
        `Expected 200 (value), got ${status}. Response: ${JSON.stringify(data).substring(0, 200)}`
      );

      // Accept 200 (if fixed) or 500 (known broken)
      expect([200, 500]).toContain(status);
      if (status === 200) {
        console.log("BUG-049 may be resolved — calculate returned 200");
      }
    });

    it("should document that calculate returns 500 for COUNT grouped UDAF (BUG-049)", async () => {
      // BUG-049: COUNT grouped UDAF calculate also broken
      const countId = createdIds[1]; // COUNT UDAF (second created in section 1)
      if (!countId) {
        console.log("SKIP: No COUNT grouped UDAF available");
        return;
      }

      const { status, data } = await post(
        `/api/tenants/udafs/${countId}/calculate`,
        undefined,
        { primaryId: 1 },
      );

      console.warn(
        `BUG-049: Calculate for COUNT grouped UDAF ${countId} → HTTP ${status}. ` +
        `Response: ${JSON.stringify(data).substring(0, 200)}`
      );

      expect([200, 500]).toContain(status);
    });

  });

  // ── 7. Footprint report (UDAF DELETE is unsupported — tests are additive) ──

  describe("7. Footprint", () => {
    it("logs the number of UDAFs created during this run", () => {
      console.log(`[udaf-grouping] Created ${createdIds.length} UDAF(s) this run (cannot delete; UDAFs are immutable).`);
    });
  });

});
